#: fuzzy search
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --no-sort --no-mouse --exact -i --tac

#: terminal bell
enable_audio_bell no

#: moves the window into a new tab
map ctrl+f3 detach_window new-tab

#: (un)zoom current window
map kitty_mod+z toggle_layout stack
